#ifndef RFL_SETTINGS_HPP_
#define RFL_SETTINGS_HPP_

#include <cstddef>
#include <type_traits>
#include <utility>

#include "Field.hpp"
#include "internal/StringLiteral.hpp"
#include "internal/field_index_by_name.hpp"
#include "internal/field_index_from_ptm.hpp"
#include "internal/get_field_names.hpp"
#include "internal/get_ith_field_from_fake_object.hpp"
#include "replace.hpp"

namespace rfl::internal {

template <auto FieldPtr, class ExpectedOwner>
struct member_ptr_traits : std::false_type {};

template <class Owner, class FieldType, FieldType Owner::* FieldPtr,
          class ExpectedOwner>
struct member_ptr_traits<FieldPtr, ExpectedOwner>
    : std::bool_constant<std::is_same_v<Owner, ExpectedOwner> &&
                         std::is_const_v<FieldType>> {};

template <auto FieldPtr, class ExpectedOwner>
concept const_member_of = member_ptr_traits<FieldPtr, ExpectedOwner>::value;

/// Returns a copy of `_obj` with the field designated by `FieldPtr` replaced
/// by `_value`. Used as the body of the with() method generated by
/// RFL_SETTINGS_OPS. Field name is recovered through the fake-object path
/// that the rest of reflect-cpp uses, so MSVC parses it correctly.
template <class T, auto FieldPtr>
  requires const_member_of<FieldPtr, T>
T settings_with_replaced(
    const T& _obj,
    std::remove_const_t<
        std::remove_reference_t<decltype(std::declval<T>().*FieldPtr)>>
        _value) {
  constexpr std::size_t I = field_index_v<T, FieldPtr>;
  static_assert(
      I != static_cast<std::size_t>(-1),
      "FieldPtr does not refer to a non-static data member of T. "
      "Make sure you pass &T::field, where field is declared inside T.");
  constexpr auto name =
      get_field_name_str_lit<T, fake_field_ptr_for_name_lookup<T, I>()>();
  return rfl::replace(_obj, rfl::make_field<name>(std::move(_value)));
}

/// Returns a copy of `_obj` with the field with the given Name replaced by
/// `_value`. Used as the body of the with<"name">() overload generated by
/// RFL_SETTINGS_OPS.
template <class T, StringLiteral Name>
T settings_with_replaced_by_name(
    const T& _obj,
    field_value_type_at_t<T, field_index_by_name_v<T, Name>> _value) {
  constexpr std::size_t I = field_index_by_name_v<T, Name>;
  static_assert(I != static_cast<std::size_t>(-1),
                "No field with the given name exists in T.");
#ifdef _MSC_VER
  static_assert(ith_field_is_const<T, static_cast<int>(I)>(),
                "Fields in Settings structs must be const.");
#endif
  return rfl::replace(_obj, rfl::make_field<Name>(std::move(_value)));
}

}  // namespace rfl::internal

/// Defines the standard with<&T::field>(value) and with<"field">(value)
/// accessors inside a settings struct. The struct must be a flat aggregate
/// (no base classes). Fields should be declared const so the only way to
/// mutate them is via with(), which returns a new copy with the chosen field
/// replaced. Place the macro at the end of the struct body, after all data
/// members.
///
/// Usage:
///   struct MySettings {
///     const int some_option = 42;
///     RFL_SETTINGS_OPS(MySettings)
///   };
///
///   auto a = MySettings{}.with<&MySettings::some_option>(100);
///   auto b = MySettings{}.with<"some_option">(100);
#define RFL_SETTINGS_OPS(Derived)                                              \
  template <auto FieldPtr>                                                     \
    requires ::rfl::internal::const_member_of<FieldPtr, Derived>               \
  Derived with(std::remove_const_t<std::remove_reference_t<                    \
                   decltype(std::declval<Derived>().*FieldPtr)>>               \
                   _value) const {                                             \
    return ::rfl::internal::settings_with_replaced<Derived, FieldPtr>(         \
        *this, std::move(_value));                                             \
  }                                                                            \
  template <::rfl::internal::StringLiteral Name>                               \
  Derived with(::rfl::internal::field_value_type_at_t<                         \
               Derived,                                                        \
               ::rfl::internal::field_index_by_name_v<Derived, Name>>          \
                   _value) const {                                             \
    return ::rfl::internal::settings_with_replaced_by_name<Derived, Name>(     \
        *this, std::move(_value));                                             \
  }

#endif
