name: test

on: [ push, pull_request ]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++
      - name: Compile 
        run: |
          g++ --version
          cmake -S . -B build -DREFLECTCPP_BUILD_TESTS=ON -DREFLECTCPP_BUILD_BENCHMARKS=ON -DREFLECTCPP_BSON=ON -DREFLECTCPP_CBOR=ON -DREFLECTCPP_FLEXBUFFERS=ON -DREFLECTCPP_MSGPACK=ON -DREFLECTCPP_TOML=ON -DREFLECTCPP_XML=ON -DREFLECTCPP_YAML=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j 4
      - name: Run tests 
        run: |
          ./build/tests/bson/reflect-cpp-bson-tests
          ./build/tests/cbor/reflect-cpp-cbor-tests
          ./build/tests/flexbuffers/reflect-cpp-flexbuffers-tests
          ./build/tests/json/reflect-cpp-json-tests
          ./build/tests/msgpack/reflect-cpp-msgpack-tests
          ./build/tests/toml/reflect-cpp-toml-tests
          ./build/tests/xml/reflect-cpp-xml-tests
          ./build/tests/yaml/reflect-cpp-yaml-tests
      - name: Run benchmarks
        run: |
          ./build/benchmarks/json/reflect-cpp-json-benchmarks
