name: test

on: [ push, pull_request ]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++
      - name: Compile 
        run: |
          g++ --version
          cmake -S . -B build -DREFLECTCPP_BUILD_BENCHMARKS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j 4
      - name: Run benchmarks
        uses: buildingcash/json-to-markdown-table-action@v1
        id: table
        with:
          json: ${{ ./build/benchmarks/all/reflect-cpp-all-format-benchmarks --benchmark_filter=canada_read --benchmark_out_format=json }}
      - run: echo ${{ steps.table.outputs.table }} >> $GITHUB_STEP_SUMMARY
