name: windows

on: [ push, pull_request ]

env: 
    VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  windows-msvc:
    strategy:
      fail-fast: false
      matrix:
        include:
          - format: JSON 
          - format: AVRO 
          - format: BSON 
          - format: CAPNPROTO 
          - format: CBOR
          - format: FLEXBUFFERS 
          - format: MSGPACK
          - format: XML 
          - format: TOML 
          - format: UBJSON 
          - format: YAML
    name: "windows-msvc (${{ matrix.format }})"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/run-vcpkg@v11
      - name: Compile
        run: |
          if [[ "${{ matrix.format }}" == "JSON" ]]; then
            cmake -S . -B build -DCMAKE_CXX_STANDARD=20 -DREFLECTCPP_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
          else
            cmake -S . -B build -DCMAKE_CXX_STANDARD=20 -DREFLECTCPP_BUILD_TESTS=ON -DREFLECTCPP_JSON=OFF -DREFLECTCPP_${{ matrix.format }}=ON -DCMAKE_BUILD_TYPE=Release
          fi
          cmake --build build --config Release -j4 
      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure
 
